version: "3.9"

services:
  bookify.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443:http://+:80
      # - ASPNETCORE_HTTP_PORTS=5000
      # - ASPNETCORE_HTTPS_PORTS=5001
    ports:
      - "80"
      - 5001:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
